version: '2'
services:
    sose-app:
        image: sose
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sose-postgresql:5432/sose
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sose-postgresql:
        extends:
            file: postgresql.yml
            service: sose-postgresql
